### ISSUE TITLE
No Way to Cancel Creation of Project, Feed, etc.

### ISSUE THREAD

**Issue by demory** [catalogueglobal/datatools-ui#84] opened 2018-05-01 16:23 UTC
It should be possible to cancel out of the creation of a new Project or FeedSource by pressing the Escape button in the text field that is presented to enter the name of the new Project/Feed.

Current "Escape" behavior is odd. Pressing Escape in a Project creation causes the name to change to "(none)" with the project showing up as an (apparently) created project in the list, but clicking through to it brings an error screen. For FeedSources, pressing Escape causes the name to change to "(none)", but it switches back to an editable field when mouse is moved out and back over.

**Comment by demory** [comment] 2018-05-01 16:35
Related to this, for creating feed sources, mousing out of the input box clears the entry

**Comment by landonreed** [comment] 2018-05-01 17:01
This is partially a duplicate of #21.  The UI for creating projects and feeds is intended to be replaced with a modal UI on the [`create-project-and-feed`](https://github.com/catalogueglobal/datatools-ui/tree/create-project-and-feed) branch; however, this has been on hold while the MapDB replacement work has been happening.

**Comment by landonreed** [comment] 2018-11-13 19:03
Will be fixed one #41 is merged.

**Closed as completed by landonreed** 2018-11-13 19:03 UTC
Labels: bug
